# Generated by Django 5.0.9 on 2024-09-18 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FinancingOfGrossFiscalDeficit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        db_collation="Latin1_General_CI_AS",
                        db_column="Country",
                        max_length=50,
                    ),
                ),
                (
                    "srcyear",
                    models.CharField(
                        db_collation="Latin1_General_CI_AS",
                        db_column="srcYear",
                        max_length=50,
                    ),
                ),
                (
                    "gross_fiscal_deficit_gfd",
                    models.IntegerField(
                        blank=True, db_column="Gross_Fiscal_Deficit_GFD", null=True
                    ),
                ),
                (
                    "internal_financing_of_market_borrowings",
                    models.IntegerField(
                        blank=True,
                        db_column="Internal_financing_of_market_borrowings",
                        null=True,
                    ),
                ),
                (
                    "internal_financing_of_national_social_security_fund_nssf_or_small_savings",
                    models.IntegerField(
                        blank=True,
                        db_column="Internal_financing_of_National_Social_Security_Fund_NSSF_or_small_savings",
                        null=True,
                    ),
                ),
                (
                    "internal_financing_of_state_provident_funds",
                    models.SmallIntegerField(
                        blank=True,
                        db_column="Internal_financing_of_state_provident_funds",
                        null=True,
                    ),
                ),
                (
                    "internal_financing_of_special_deposits",
                    models.SmallIntegerField(
                        blank=True,
                        db_column="Internal_financing_of_special_deposits",
                        null=True,
                    ),
                ),
                (
                    "internal_financing_of_drawdown_of_cash_balances",
                    models.IntegerField(
                        blank=True,
                        db_column="Internal_financing_of_drawdown_of_cash_balances",
                        null=True,
                    ),
                ),
                (
                    "internal_financing_with_financing_from_other_sources",
                    models.IntegerField(
                        blank=True,
                        db_column="Internal_financing_with_financing_from_other_sources",
                        null=True,
                    ),
                ),
                (
                    "external_financing",
                    models.IntegerField(
                        blank=True, db_column="External_financing", null=True
                    ),
                ),
                ("yearcode", models.SmallIntegerField(db_column="YearCode")),
                (
                    "year",
                    models.CharField(
                        db_collation="Latin1_General_CI_AS",
                        db_column="Year",
                        max_length=50,
                    ),
                ),
            ],
            options={
                "db_table": "Financing of Gross Fiscal Deficit",
                "managed": False,
            },
        ),
        migrations.DeleteModel(
            name="FinancingOfGrossFiscalDeficitOfTheCentralGovernment",
        ),
    ]
